export const FETCH_NEWS_LIST = "App/Home/FETCH_NEWS_LIST";
export const FETCH_NEWS_LIST_DONE = "App/Home/FETCH_NEWS_LIST_DONE";

export const FETCH_PUBLISHER_NEWS_LIST = "App/Home/FETCH_PUBLISHER_NEWS_LIST";
export const FETCH_PUBLISHER_NEWS_LIST_DONE =
  "App/Home/FETCH_PUBLISHER_NEWS_LIST_DONE";
